### ISSUE TITLE
Doesn't work right away

### ISSUE THREAD

**Issue by tapochek666** [symbuzzer/livebootmodule#11]
It doesn’t work right away. First, part of the standard animation appears, and only then the liveboot itself

**Comment by symbuzzer** [comment]
Which device, os, root tool etc?

**Comment by tapochek666** [comment]
Redmi 10, custom firmware Everest OS v1.2 - Unofficial, android 14, Magisk

ср, 5 июн. 2024 г. в 05:06, Ali Beyaz ***@***.***>:

**Comment by tapochek666** [comment]
So? I provided the information. So what next?

**Comment by tapochek666** [comment]
I installed liveboot and the same thing. Standard animation for a couple of seconds, then liveboot.

**Comment by symbuzzer** [comment]
So I cant fix. I only create module from app. Please report this to Chainfire's Liveboot Github Repo.
