### ISSUE TITLE
How to turn back to original boot animation?

### ISSUE THREAD

**Issue by Abinpj1** [symbuzzer/livebootmodule#13]
So if I flash this module, how do I revert back the my original boot animation? I'm actually using a custom rom with custom boot animation, so if I flash this and unflash this after some time will my previous boot animation come back ?

**Comment by Sinneida** [comment]
Since this is a systemless module, you should get back to original animation when the module gets removed. 😅

**Comment by Abinpj1** [comment]
> Since this is a systemless module, you should get back to original animation when the module gets removed. 😅

Thanks alot
