### ISSUE TITLE
Doesn't work on MIUI 12.5.6 by Xiaomi.eu

### ISSUE THREAD

**Issue by Strelitzia786** [symbuzzer/livebootmodule#3]

**Comment by symbuzzer** [comment]
Can u install liveboot app from Google Play and check if it works?

**Comment by symbuzzer** [comment]
So not supported by official app :( @Strelitzia786

**Comment by Strelitzia786** [comment]
> So not supported by official app :( @Strelitzia786 

No idk why. Any proper reason? I use the MIUI 12.5.6 by xiaomi EU ROMs

**Comment by symbuzzer** [comment]
I dont know too

**Comment by NxMaDxN** [comment]
> Can u install liveboot app from Google Play and check if it works?

it work for me with miui.eu rom (the app work fine... but not the module)
model: Mi 10t pro
miui version : 13.0.7.0.SJDCNXM
