### ISSUE TITLE
Boot stages and Error Logs instead of whole dmesg/logcat

### ISSUE THREAD

**Issue by MarkusTieger** [symbuzzer/livebootmodule#7]
To make it a little more useful and more unix-like: I think it would be better if you only see the successful boot stages in a systemd style and ofc. all error messages. At the current version, there are so many messages, that you can't read them all.

That means like so: (Image from Wikipedia)
![image](https://github.com/symbuzzer/livebootmodule/assets/77546847/1c55dd3c-df43-4f17-9c2f-ee69f7594c26)

**Comment by irresistibl** [comment]
Agreed. This makes more sense for the usage of this

**Comment by symbuzzer** [comment]
These are possible already, thanks to Chainfire and his liveboot app. However I am waiting an example of KernelSU's brand new module config html interface.

**Comment by symbuzzer** [comment]
Understand now. This is basic module version of Chainfire's Liveboot app. So I cant add any feature that not exists on app. So you should ask to Chainfire from Liveboot repo sir
