### ISSUE TITLE
Better comparison with the upstream LiveBoot

### ISSUE THREAD

**Issue by axelkar** [symbuzzer/livebootmodule#8]
What does this fork do better? You should probably add that the upstream LiveBoot doesn't have a Magisk module.

**Comment by symbuzzer** [comment]
Liveboot is an application which has icon on launcher and many customisation options in it.

Mine is a module which hasnt both of these features. Also already based original Chainfire's app. Thanks to him for app and gives permission to me creating module of his app.

Personally, I didnt want to an icon for verbose boot feature on my launcher. So I created this module
